### ISSUE TITLE
StringW became StringL, broken :(

### ISSUE THREAD

**Issue by Fernthedev** [sc2ad/beatsaber-hook#111]
Tracking the issue here because why not

**Comment by sc2ad** [comment]
To add more info here:
- Seems as if `StringW` conversion to std::string is incorrect
- The conversion from utf16 to utf8 should be moved to `to_utf8`
- `StringW` should call the `csstrtostr`/`to_utf8` methods (ideally shortcut for utf8 string)
- Namespace tainting from `detail` needs to be changed and fixed.

**Comment by sc2ad** [comment]
This has been resolved on latest. See v3.6.1+
