### ISSUE TITLE
StringW operator std::string issue

### ISSUE THREAD

**Issue by RedBrumbler** [sc2ad/beatsaber-hook#116]
Making an issue of this since I am unsure how to proceed with it.

it seems that operator std::string consistently returns the contained string to be off by 1, meaning the last character is erased or somehow inaccessible

Only the operator std::string itself seems to be suffering from this, the rest of the operators are fine

![image](https://user-images.githubusercontent.com/51795403/151587735-67bb2ae6-3a49-464f-a5e4-177bab8cae5e.png)

![image](https://user-images.githubusercontent.com/51795403/151587716-5f31ad49-97dd-4188-b7da-cf41663c2b9e.png)

I think this could be solved by either removing the -1 [here](https://github.com/sc2ad/beatsaber-hook/blob/fd32e216408352cdfdf7f048699ffee70abb5ff9/src/utils/typedefs-wrapper.cpp#L38) or by not assigning the \0 [here](https://github.com/sc2ad/beatsaber-hook/blob/fd32e216408352cdfdf7f048699ffee70abb5ff9/src/utils/typedefs-wrapper.cpp#L37)

The reason I am unsure on how to proceed is that I do not know if it's the first thing that is broken, or the second thing

**Comment by RedBrumbler** [comment]
Removing both options I mentioned seems to make it operate properly

![image](https://user-images.githubusercontent.com/51795403/151597555-b6865a3c-0872-4046-a0c8-4dbd5d48241d.png)

(same test code as above)

![image](https://user-images.githubusercontent.com/51795403/151597537-59c271f2-ed58-46b3-b416-c5b7f1859538.png)

**Comment by sc2ad** [comment]
Resolved in latest.
